version: '3.8'
services:
    zoo1:
        image: confluentinc/cp-zookeeper:7.3.2
        hostname: zoo1
        container_name: zoo1
        networks:
            - kafka-network
        ports:
          - "2181:2181"
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_SERVER_ID: 1
          ZOOKEEPER_SERVERS: zoo1:2888:3888;zoo2:2888:3888;zoo3:2888:3888

    zoo2:
        image: confluentinc/cp-zookeeper:7.3.2
        hostname: zoo2
        container_name: zoo2
        networks:
            - kafka-network
        ports:
          - "2182:2182"
        environment:
          ZOOKEEPER_CLIENT_PORT: 2182
          ZOOKEEPER_SERVER_ID: 2
          ZOOKEEPER_SERVERS: zoo1:2888:3888;zoo2:2888:3888;zoo3:2888:3888

    zoo3:
        image: confluentinc/cp-zookeeper:7.3.2
        hostname: zoo3
        container_name: zoo3
        networks:
            - kafka-network
        ports:
          - "2183:2183"
        environment:
          ZOOKEEPER_CLIENT_PORT: 2183
          ZOOKEEPER_SERVER_ID: 3
          ZOOKEEPER_SERVERS: zoo1:2888:3888;zoo2:2888:3888;zoo3:2888:3888

    kafka1:
        image: confluentinc/cp-kafka:latest
        hostname: kafka1
        container_name: kafka1
        networks:
            - kafka-network
        ports:
            - "8097:8097"
        depends_on:
            - zoo1
            - zoo3
            - zoo2
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182,zoo3:2183"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:8097,INTERNAL://kafka1:9091
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        volumes:
            - ./kafka/broker-1:/var/lib/kafka/data
    kafka2:
        image: confluentinc/cp-kafka:latest
        hostname: kafka2
        container_name: kafka2
        networks:
            - kafka-network
        ports:
            - "8098:8098"
        depends_on:
            - zoo1
            - zoo2
            - zoo3
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182,zoo3:2183"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:8098,INTERNAL://kafka2:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        volumes:
            - ./kafka/broker-2:/var/lib/kafka/data
    kafka3:
        image: confluentinc/cp-kafka:latest
        hostname: kafka3
        container_name: kafka3
        networks:
            - kafka-network
        ports:
          - "8099:8099"
        depends_on:
          - zoo1
          - zoo2
          - zoo3
        environment:
          KAFKA_BROKER_ID: 3
          KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2182,zoo3:2183"
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:8099,INTERNAL://kafka3:9093
          KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        volumes:
            - ./kafka/broker-3:/var/lib/kafka/data
    schema-registry:
        image: confluentinc/cp-schema-registry:latest
        hostname: schema-registry
        networks:
          - kafka-network
        depends_on:
            - zoo1
            - zoo2
            - zoo3
            - kafka3
            - kafka2
            - kafka1
        ports:
            - "8081:8081"
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka3:9093,PLAINTEXT://kafka3:9091,PLAINTEXT://kafka3:9092
            SCHEMA_REGISTRY_DEBUG: 'true'

networks:
    kafka-network:
        driver: bridge