version: '3.8'
services:
    zoo1:
        image: zookeeper
        restart: always
        hostname: zoo1
        networks:
            - kafka-network
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
        volumes:
            - ./kafka/zk-1:/var/lib/zookeeper/data

    zoo2:
        image: zookeeper
        restart: always
        hostname: zoo2
        networks:
            - kafka-network
        ports:
            - 2182:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
        volumes:
            - ./kafka/zk-2:/var/lib/zookeeper/data

    zoo3:
        image: zookeeper
        restart: always
        hostname: zoo3
        networks:
            - kafka-network
        ports:
            - 2183:2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
        volumes:
            - ./kafka/zk-3:/var/lib/zookeeper/data
    kafka1:
        image: confluentinc/cp-kafka:latest
        hostname: kafka1
        container_name: kafka1
        networks:
            - kafka-network
        ports:
            - "8097:8097"
        depends_on:
            - zoo1
            - zoo3
            - zoo2
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: EXTERNAL://kafka1:8097,INTERNAL://kafka1:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        volumes:
            - ./kafka/broker-1:/var/lib/kafka/data
    kafka2:
        image: confluentinc/cp-kafka:latest
        hostname: kafka2
        container_name: kafka2
        networks:
            - kafka-network
        ports:
            - "8098:8098"
        depends_on:
            - zoo1
            - zoo2
            - zoo3
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: EXTERNAL://kafka2:8098,INTERNAL://kafka2:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        volumes:
            - ./kafka/broker-2:/var/lib/kafka/data
    kafka3:
        image: confluentinc/cp-kafka:latest
        hostname: kafka3
        container_name: kafka3
        networks:
            - kafka-network
        ports:
          - "8099:8099"
        depends_on:
          - zoo1
          - zoo2
          - zoo3
        environment:
          KAFKA_BROKER_ID: 3
          KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: EXTERNAL://kafka3:8099,INTERNAL://kafka3:9092
          KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        volumes:
            - ./kafka/broker-3:/var/lib/kafka/data
    schema-registry:
        image: confluentinc/cp-schema-registry:latest
        hostname: schema-registry
        networks:
          - kafka-network
        depends_on:
            - zoo1
            - zoo2
            - zoo3
            - kafka3
            - kafka2
            - kafka1
        ports:
            - "8081:8081"
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka2:9092,PLAINTEXT://kafka1:9092,PLAINTEXT://kafka3:9092
            SCHEMA_REGISTRY_DEBUG: 'true'

networks:
    kafka-network:
        driver: bridge